import { Platform } from 'react-native';

const fonts = {
  regular: Platform.select({
    ios: 'Poppins-Regular',
    android: 'Poppins-Regular',
    default: 'Poppins-Regular',
  }),
  medium: Platform.select({
    ios: 'Poppins-Medium',
    android: 'Poppins-Medium',
    default: 'Poppins-Medium',
  }),
  semiBold: Platform.select({
    ios: 'Poppins-SemiBold',
    android: 'Poppins-SemiBold',
    default: 'Poppins-SemiBold',
  }),
  bold: Platform.select({
    ios: 'Poppins-Bold',
    android: 'Poppins-Bold',
    default: 'Poppins-Bold',
  }),
  extraBold: Platform.select({
    ios: 'Poppins-ExtraBold',
    android: 'Poppins-ExtraBold',
    default: 'Poppins-ExtraBold',
  }),
};

export const theme = {
  fonts,
  colors: {
    primary: '#9C27B0',
    primaryDark: '#7B1FA2',
    primaryLight: '#CE93D8',
    primaryMuted: 'rgba(156, 39, 176, 0.12)',
    secondary: '#E91E63',
    secondaryDark: '#C2185B',
    secondaryMuted: 'rgba(233, 30, 99, 0.10)',
    accent: '#FFD700',
    background: '#FFFFFF',
    backgroundSoft: '#FDF8FC',
    surface: '#F5F0F8',
    surfaceElevated: '#FFFFFF',
    text: '#1A1A2E',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    error: '#E53935',
    success: '#43A047',
    white: '#FFFFFF',
    black: '#000000',
    border: '#E8E0ED',
    card: '#FFFFFF',
    overlay: 'rgba(26, 26, 46, 0.55)',
    chatMine: '#9C27B0',
    chatOther: '#F3E8F7',
  },
  darkColors: {
    primary: '#CE93D8',
    secondary: '#F48FB1',
    accent: '#FFD700',
    background: '#121212',
    surface: '#1E1E1E',
    text: '#FFFFFF',
    textSecondary: '#B0B0B0',
    error: '#CF6679',
    success: '#81C784',
    white: '#FFFFFF',
    black: '#000000',
    border: '#333333',
    card: '#1E1E1E',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    full: 999,
  },
  shadows: {
    sm: {
      shadowColor: '#9C27B0',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    md: {
      shadowColor: '#1A1A2E',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 6,
    },
    lg: {
      shadowColor: '#E91E63',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 24,
      elevation: 10,
    },
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
    },
  },
  typography: {
    h1: {
      fontFamily: fonts.extraBold,
      fontSize: 32,
      fontWeight: '800' as const,
    },
    h2: {
      fontFamily: fonts.bold,
      fontSize: 24,
      fontWeight: '700' as const,
    },
    h3: {
      fontFamily: fonts.semiBold,
      fontSize: 20,
      fontWeight: '600' as const,
    },
    body: {
      fontFamily: fonts.regular,
      fontSize: 16,
      fontWeight: '400' as const,
    },
    caption: {
      fontFamily: fonts.regular,
      fontSize: 12,
      fontWeight: '400' as const,
    },
  },
};
