export const MOCK_PROFILES = [
  {
    id: '1',
    name: 'Ananya Sharma',
    age: 26,
    profession: 'Software Engineer',
    religion: 'Hindu',
    bio: 'Love traveling and exploring new cuisines. Looking for someone who shares the same passion.',
    location: 'Mumbai, Maharashtra',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    distance: 2,
    isVerified: true,
  },
  {
    id: '2',
    name: 'Priya Patel',
    age: 24,
    profession: 'Doctor',
    religion: 'Hindu',
    bio: 'Compassionate and dedicated. I love reading and quiet evenings.',
    location: 'Ahmedabad, Gujarat',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    distance: 5,
    isVerified: true,
  },
  {
    id: '3',
    name: 'Rahul Verma',
    age: 28,
    profession: 'Architect',
    religion: 'Sikh',
    bio: 'Design is my life. I enjoy sketching and morning runs.',
    location: 'Delhi, India',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
    distance: 10,
    isVerified: false,
  },
  {
    id: '4',
    name: 'Zara Khan',
    age: 25,
    profession: 'Graphic Designer',
    religion: 'Muslim',
    bio: 'Creative soul with a love for abstract art and coffee.',
    location: 'Bangalore, Karnataka',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
    distance: 3,
    isVerified: true,
  },
];
